# SPDX-FileCopyrightText: Copyright (C) 2021-2026 Software Radio Systems Limited
# SPDX-License-Identifier: BSD-3-Clause-Open-MPI

include:
  - local: .gitlab/ci-shared/versions.yml

.deb-package:
  image: ${OCUDU_PACKAGING_REGISTRY_URI}/ubuntu_${OS_VERSION}_img_pkg:$UBUNTU_PACKAGING_VERSION
  variables:
    OS_VERSION: "22.04"
    REPO_URL: https://gitlab-ci-token:${CI_JOB_TOKEN}@${CI_SERVER_HOST}:${CI_SERVER_PORT}/${CI_PROJECT_PATH}.git
    PROJECT_NAME: $CI_PROJECT_NAME
    RELEASE_VERSION: "0.1"
    MINOR_VERSION: "1"
    GIT_STRATEGY: none
  script:
    - REFERENCE=${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA:-$CI_COMMIT_SHA}
    - make_orig_tarball.sh $REPO_URL $REFERENCE $PROJECT_NAME $RELEASE_VERSION
    - package.sh $PROJECT_NAME $RELEASE_VERSION $MINOR_VERSION
    - dpkg.sh $PROJECT_NAME $RELEASE_VERSION $MINOR_VERSION
    - mv ~/build-area/${PROJECT_NAME}_${RELEASE_VERSION}/minor_v${MINOR_VERSION}/${PROJECT_NAME}_${RELEASE_VERSION}-0ubuntu1ppa${MINOR_VERSION}~${OS_VERSION}_amd64.deb ${CI_PROJECT_DIR}/
  artifacts:
    paths:
      - ${PROJECT_NAME}_${RELEASE_VERSION}-0ubuntu1ppa${MINOR_VERSION}~${OS_VERSION}_amd64.deb
    when: on_success
    expire_in: "1 day"

.deb-install:
  image: ubuntu:$OS_VERSION
  variables:
    OS_VERSION: "22.04"
    PROJECT_NAME: $CI_PROJECT_NAME
    RELEASE_VERSION: "0.1"
    MINOR_VERSION: "1"
    GIT_STRATEGY: none
  before_script:
    - apt update
    - DEBIAN_FRONTEND='noninteractive' TZ='Europe/London' apt install ./${PROJECT_NAME}_${RELEASE_VERSION}-0ubuntu1ppa${MINOR_VERSION}~${OS_VERSION}_amd64.deb -y
